name: 'Deploy to GitHub Pages'
description: 'Build and deploy React app to GitHub Pages'
inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
    default: '20'
runs:
  using: 'node20'
  main: 'main.js'
